version: "3"

services:
  web:
    container_name: resume-parser
    build:
      context: .
      dockerfile: .docker/Dockerfile
    # command: python3 manage.py runserver 7000
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    env_file:
      - .docker/.env
    # working_dir: /app/resume_parser
